version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
<<<<<<< Updated upstream
    - requirements: Docs/requirements.txt
=======
    - requirements: docs/requirements.txt 
    - method: pip
      path: .
>>>>>>> Stashed changes

sphinx:
  configuration: Docs/conf.py
