[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GReS"
authors = [{name = "University of Padova Contributors", email = "daniele.moretto.3@phd.unipd.it"}]
dynamic = ["version", "description"]
